### ISSUE TITLE
Is Magnetic Sensor required?

### ISSUE THREAD

**Issue by FireRat-137** [Frazew/VirtualSensor#10]
All three gyroscope axies display on 0. Magnetic sensor however, displays "false" (so I guess I don't have it). Is this sensor required for the virtual gyro to work? (if not, do you know of any other module to virtualize it? =P)
By the way, the Settings does not seem to work (unless they are yet coded, which I'd understand ;) )

Keep up the good work though, Pokemon Go should really not need the damn gyroscope if Android Camera can run this perfectly-working panoramic photo capture function...

**Comment by frazew** [comment]
Yes, the magnetic sensor _is_ needed. There is no way to make this work without it, sorry :/
I should have removed that Settings button from the release, it's not supposed to do anything yet and it's confusing many people.
