### ISSUE TITLE
It does not work on the SM-G530BT

### ISSUE THREAD

**Issue by zezinbm** [Frazew/VirtualSensor#11]
tested it on my SM- G530BT and did not work , it supports android 4.4.4 ?
sorry for the mistakes , I'm posting with the google translator

**Comment by frazew** [comment]
Could you give more details ? Is the gyroscope detected but not giving any values or is it not working at all ? Can you send the xposed log ?

**Comment by zezinbm** [comment]
this is the problem I'm half lay in this part , I am searching here for how to do to put the log here

**Comment by zezinbm** [comment]
![screenshot_2016-08-06-13-34-39](https://cloud.githubusercontent.com/assets/20864557/17457962/9b5d77e8-5bdb-11e6-9208-592836cfc0fa.png)

**Comment by zezinbm** [comment]
fiz a instalacao do xpoded , reiniciei o aparelho e funcionou, obrigado pela ajuda, pode trancar o topico

**Comment by zezinbm** [comment]
he worked in gyrotest , managed to install the card board , but in the games he did not budge

**Comment by zezinbm** [comment]
I did a hard reset on the device, I installed Xposed after the virtual senssor , and nothing worked , the app opens , appears the indications of senssor , but the game works not

**Comment by frazew** [comment]
From the screenshot you sent, it appears you did not install the correct Xposed version for you android version. If this is really the case, you will need to fix this in order for the module to work.

**Comment by zezinbm** [comment]
I managed to install the current version of Xposed before I could install the card board after putting the virtual sensor, now not even that, all gyroscope testing application work , not only works in games, bombsqad type , if not meche

**Comment by zezinbm** [comment]
![screenshot_2016-08-06-16-11-10 1](https://cloud.githubusercontent.com/assets/20864557/17459190/e571ecdc-5c04-11e6-8c47-90cf091643df.png)
![screenshot_2016-08-06-16-17-20 1](https://cloud.githubusercontent.com/assets/20864557/17459225/afe03974-5c05-11e6-968d-d5da264b573d.png)
![screenshot_2016-08-06-16-17-30 1](https://cloud.githubusercontent.com/assets/20864557/17459227/b55373bc-5c05-11e6-8619-da0db8c15af3.png)
![screenshot_2016-08-06-16-18-31 1](https://cloud.githubusercontent.com/assets/20864557/17459234/cd72d15e-5c05-11e6-98be-4c3c96aab148.png)

**Comment by frazew** [comment]
I guess that means I can close this issue then.
