### ISSUE TITLE
Galaxy J7

### ISSUE THREAD

**Issue by FireAballus** [Frazew/VirtualSensor#17]
Bro, congrats for your work. But, i'm having trouble here, because my device don't have magnetic sensors... can u do a version of this app without it? :( tks

**Comment by frazew** [comment]
Hey ! Unfortunately, this is impossible, I should add this somewhere (Although I think I already did). It's not that I don't want to do it, it's basically impossible. A compass is _mandatory_ in order for this module to work. Sorry :/ (Just in case, I'm open to any suggestions, but I really don't see how that would be done).
