### ISSUE TITLE
Android rotation vector stops working. 

### ISSUE THREAD

**Issue by ff2009** [Frazew/VirtualSensor#2]
When  I enable the module, on xposed, after rebooting the phone my android rotation vector doesn't work anymore. 
Disabling the module a rebooting the phone makes it work again. My phone is an lg-l90.

**Comment by frazew** [comment]
That's weird. Could you upload the xposed log just in case if possible ?

**Comment by ff2009** [comment]
Here it is.
By the way. I noticed that the mix of sensors is not very accurated.
When I through the phone up in the air rotating when  he fall he doesn't know in witch position he was before. Is it possible to assign the android rotation vector to the gyroscope.
I use the sensor fusion to do this test.

On Wed, Jul 27, 2016 at 7:04 PM +0100, "Frazew" <notifications@github.com<mailto:notifications@github.com>> wrote:

That's weird. Could you upload the xposed log just in case if possible ?

##

**Comment by frazew** [comment]
Latest version (v1.31) should fix this. If I understood the problem correctly, what happened with previous versions is that existing sensors were sometimes replaced by the virtual sensors. This should now be fixed. Could you test and report any further issues ?

**Comment by ff2009** [comment]
I have tried the new update, with the version (v1.32) on 2 different devices, and I will send you the xposed logs, and some screen shots, from the CPU-Z on the sensors tab, with the module enable and disable.

LG-L90:
 module enable:
- the google camera show the panorama and photosphere options and both work (but the sensors are very inaccurate) (It's impossible to take a complete photo sphere).
- On the sensor fusion app, the android rotation vector still, not working. (I know it still a early build, but the virtual sensor, on sensor fusion, lost track, of it's orientation, when, I through the phone around.
- On CPU-Z, only the accelerometer, and the magnetometer work.
- On Just Cause 3 wingsuit app, the gyroscope worked on the last version 1.2, I think (very inaccurate, but I could see, that was doing something), and now doesn't do nothing.

Wiko Wax:
 module enable:
- The CPU-Z show all virtual sensors enable, and they seem to work.
- On Sensor Fusion, the android rotation vector isn't on the default position, but it's static. The gyroscope is on the default position, and don't move either.

By the way, took a look at this project if you hadn't already:
https://bitbucket.org/apacha/sensor-fusion-demo/

I hope I could help.

![lgl90_module_disable](https://cloud.githubusercontent.com/assets/7131634/17252875/3e23fea2-55a6-11e6-9dfb-cfbcb4728678.png)
![lgl90_module_enable_1](https://cloud.githubusercontent.com/assets/7131634/17252878/3e2f98d4-55a6-11e6-8223-a8d7a8c5568b.png)
![lgl90_module_enable_2](https://cloud.githubusercontent.com/assets/7131634/17252876/3e28fb46-55a6-11e6-855d-16928ba21db1.png)

![wax_module_disable](https://cloud.githubusercontent.com/assets/7131634/17252877/3e2f4adc-55a6-11e6-9902-8f92d6d8138c.png)
![wax_module_enable](https://cloud.githubusercontent.com/assets/7131634/17252879/3e306d54-55a6-11e6-8d20-96efce6fd85c.png)

[lgl90_xposed_error_20160729_152144.log.txt](https://github.com/Frazew/VirtualSensor/files/390803/lgl90_xposed_error_20160729_152144.log.txt)
[wax_xposed_error_20160729_151248.log.txt](https://github.com/Frazew/VirtualSensor/files/390802/wax_xposed_error_20160729_151248.log.txt)

**Comment by frazew** [comment]
First of all, thanks for the very detailed information !

The log for your lgl90 has an exceptions I did not expect to find, it's very useful. This explains why your device does not detect the sensors, they don't seem to be correctly added to the sensors list. I think the issue is that your device already has quite a lot of sensors this mod is supposed to add, I thought I had a check not to override existing sensors, but it seems it doesn't work very well. 

As for the wax log, two possibilities : the main exception thrown on many other devices is the issue. Or there is indeed a particular issue that causes the magnetic to stop reading anything. I can see that on your sceenshot indeed : the magnetic sensor doesn't output anything and so do the custom sensors because of that.

**Comment by frazew** [comment]
Back with a test release, commit 40d21a35e8072eec37abe32e6ab33ce85b74196b should fix the two errors I mentioned in my previous comment. Could you please test with the attached apk, report any changes and logs ? Thanks !
[app-debug.zip](https://github.com/Frazew/VirtualSensor/files/391535/app-debug.zip)
(Had to use zip as Github doesn't like apks apparently)

**Comment by ff2009** [comment]
I tested this release on the LG L90, and seems that fix the error.

The logs doesn't seem to have anything relevant, but here it's:
[lgl90_xposed_error_20160730_005945.log.txt](https://github.com/Frazew/VirtualSensor/files/391595/lgl90_xposed_error_20160730_005945.log.txt)
[lgl90_xposed_error_20160730_005945.log.txt]

I did some more tests and here's my finding.
LG L90:
- On CPU-Z everything seems to work now properly. But I noticed a bug where sometimes the virtual sensor gyroscope disappeared. And the values always show 0 on all axis, but this always happened, with the other updates before.
  ![lgl90_screenshot_20160730-010716](https://cloud.githubusercontent.com/assets/7131634/17266773/5d9e3ca4-55f4-11e6-85ef-c84273100569.png)
- On Sensor Fusion, all sensors seemed to work, but all sensors dependent on the gyroscope, seemed to lock sometimes. Swiping between sensors, fixed this bug.
- On Just Cause 3 wingsuit. The sensor has a very strange behavior on this one. Only seems to work in the first 20 seconds, tops, and it works, very slowly, and only up and down. After I made 1 or 2 moves, it stopped working. I think it's was after playing this, that the sensor will stop showing on CPU-Z. But if I tried again with this or another app, the sensors, was working. 
- Finally on the Google Camera. I was able, to create a 360 panorama on photosphere mode (with some distortion), but as soon I tried to capture, the floor, or the roof (looking down or up), the sensor lost track from where it was). 

The log above, is after trying all these. I reboot the phone several times, and deed this tests, and compared the logs, and that's all, I found.

I didn't test with the wiko yet. But I will try it as soon as I can.

Sorry for the closed and reopened thread.

If I find, more bugs, I will let you know.
Or if you need help testing anything just say it.

**Comment by ff2009** [comment]
Just finish testing on the Wiko Wax, and the log doesn't seem to had errors related with the your module.

Log:
[wax_xposed_error_20160730_134340.log.txt](https://github.com/Frazew/VirtualSensor/files/391915/wax_xposed_error_20160730_134340.log.txt)

Wiko Wax:
- On CPU-Z some sensors apear with some values, but other only show a small diference between values, ranged from 0.0, -0.5. The only one that show some relevant data is the Gyroscope.
- On sensor fusion, all sensors are static, but only the gyroscope dependents, seems  to be doing something, because they aren't in their default position, when I launch the app. but they don't move. All the other sensors are static and in their default position. Even the compass and Accelerometer mix, but on CPU-Z, the values are fine.
  I couldn't test the Google Camera because it doesn't work, on android 4.4 anymore.

**Comment by frazew** [comment]
Thanks you for the reports. It's good to see that at least the sensors no longer get overridden.
Many people have issues with actually getting the sensors to report any values at all. I still haven't figured out why it doesn't work. From what you're saying, it might be a range issue.
