### ISSUE TITLE
It does not work on the Galaxy Grand 2

### ISSUE THREAD

**Issue by Guhdesu** [Frazew/VirtualSensor#4]
Good wanted to thank you for creating this module but it does not work on my phone has to support it? Android is 4.3 jelly bean.

**Comment by frazew** [comment]
Could you try with the newest version (v1.31) ? If that doesn't work, could you provide the xposed log too ?

**Comment by Guhdesu** [comment]
Yes I will do it now after the results speak.

**Comment by Guhdesu** [comment]
I tried it with the latest version and still did not work, here's the log http://pastebin.com/bVbBDqPu

**Comment by frazew** [comment]
Thanks for the log, I don't know why it doesn't work though as the hook should be ok. I'm really starting to think that Samsung devices have something different.

**Comment by Guhdesu** [comment]
Oh,ok I'll wait.

**Comment by frazew** [comment]
Does it work with the latest version though ?

**Comment by Guhdesu** [comment]
![screenshot_2016-08-01-13-11-31](https://cloud.githubusercontent.com/assets/20704066/17300713/e9fbc53a-57e9-11e6-83c4-4223f9ecb53c.png)
Yeah !! It worked but still could not see 360 degree videos on youtube.
