### ISSUE TITLE
Lenovo S850 Kitkat 00,00,00 value

### ISSUE THREAD

**Issue by Succubussix** [Frazew/VirtualSensor#9]
xD its not working its shows 

gyro : 00,00,00 only ace have value

sad xD heres the screen shot bro :)

https://s32.postimg.org/4tkz6rgj9/Screenshot_2016_08_03_11_59_33.jpg

**Comment by Succubussix** [comment]
i tried this on vr hunted house not working :(

**Comment by Succubussix** [comment]
i tired to test on sensor same 0,0,0 ...

**Comment by frazew** [comment]
You don't have a magbtic sensor therefore the module cannot work. I'm sorry for you :/

**Comment by Succubussix** [comment]
this makes me cry :'( and throw this phone sad thanks for info
